#!/bin/bash

echo "==============================================="
echo "PostgreSQL Password Setup for Spendy"
echo "==============================================="
echo ""
echo "We need to set up PostgreSQL authentication."
echo ""
echo "Option 1: Set a new password for your user"
echo "----------------------------------------"
echo "Run this command in your terminal:"
echo ""
echo "  psql postgres"
echo ""
echo "If it connects without asking for password, run:"
echo ""
echo "  ALTER USER aidenpete WITH PASSWORD 'spendy123';"
echo "  CREATE DATABASE spendy_db;"
echo "  \q"
echo ""
echo "Then update the .env file with:"
echo "DATABASE_URL=\"postgresql://aidenpete:spendy123@localhost:5432/spendy_db?schema=public\""
echo ""
echo ""
echo "Option 2: Find your PostgreSQL password"
echo "----------------------------------------"
echo "If you set a password during PostgreSQL installation,"
echo "you might find it in:"
echo "  - macOS Keychain (search for 'postgres')"
echo "  - ~/.pgpass file"
echo ""
echo ""
echo "Option 3: Use postgres superuser"
echo "----------------------------------------"
echo "Try connecting as postgres user:"
echo ""
echo "  psql -U postgres postgres"
echo ""
echo "Then run:"
echo ""
echo "  CREATE DATABASE spendy_db;"
echo "  \q"
echo ""
echo "And update .env with:"
echo "DATABASE_URL=\"postgresql://postgres@localhost:5432/spendy_db?schema=public\""
echo ""
echo "==============================================="
